projecticfes:
  outputs:
    dev:
      dataset: Resultados_ICFES
      job_execution_timeout_seconds: 1200
      job_retries: 1
      keyfile: .\key.json #RUTA DEL PROYECTO CON \key.json
      location: US
      method: service-account
      priority: interactive
      project: mineria-2023-402723
      threads: 1
      type: bigquery
  target: dev