version: 2

sources:
  - name: Resultados_ICFES
    database: mineria-2023-402723
    tables:
      - name: Registros_ICFES_NEW
        description: tabla con la informaci贸n de los ICFES
      - name: Registros_ICFES
        description: tabla con la informaci贸n de los ICFES
      - name: Registros_ICFES_IMP
        description: tabla con la informaci贸n ya imputada
      - name: Registros_ICFES_M
        description: tabla con la informaci贸n ya imputada